MVC_Demo/Models/Book.cs
namespace MVC_Demo.Models
{
    public class Book
    {
        public int Bid { get; set; }
        public string Bname { get; set; }
        public double Price { get; set; }
    }
}

MVC_Demo/Models/Employee.cs
using System.ComponentModel.DataAnnotations;

namespace MVC_Demo.Models;   

    public class Employee
    {
 
        [Required(ErrorMessage = "name is required")]
        [Display(Name = "Employee full name")]
        [MaxLength(30, ErrorMessage = "name must have less than 30 characters")]
        public string Name { get; set; }


        [Required(ErrorMessage = "email is required")]
        [DataType(DataType.EmailAddress, ErrorMessage = "email id is not in proper format")]
        public string Email { get; set; }


        [Required(ErrorMessage = "age is required")]
        [Range(18, 60, ErrorMessage = "age must be in between 18 -60")]

        public int Age { get; set; }


        [Required(ErrorMessage = "password is required")]
        [MaxLength(20)]
        [DataType(DataType.Password)]
        public string Password { get; set; }


        [Required(ErrorMessage = "confirm password is required")]
        [MaxLength(20)]
        [DataType(DataType.Password)]
        [Display(Name = "Confirm Password")]
        [Compare("Password", ErrorMessage = "password and confirm password does not match")]
        public string ConfirmPassword { get; set; }


        [DataType(DataType.Date)]
        public DateTime Dob { get; set; }
    }

MVC_Demo/Models/ErrorViewModel.cs
namespace MVC_Demo.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MVC_Demo/Models/Product.cs
namespace MVC_Demo.Models
{
    public class Product
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public double Price { get; set; }
    }
}

MVC_Demo/Controllers/BookController.cs
using Microsoft.AspNetCore.Mvc;
using MVC_Demo.Models;
using MVC_Demo.Views;

namespace MVC_Demo.Controllers
{
    public class BookController : Controller
    {
        public IActionResult BookList()
        {
            List<Book> books = new List<Book>()
            {
                new Book{ Bid = 1,Bname="Indian Geography",Price=200},
                new Book{ Bid = 2,Bname="Social Science",Price=260},
                new Book{ Bid = 3,Bname="Environmetal Studies",Price=670},
                new Book{ Bid = 4,Bname="English Grammer",Price=880},
                new Book{ Bid = 5,Bname="Information Technology",Price=980},
                new Book{ Bid = 6,Bname="Data Science",Price=955}
            };
            ViewData["list"] = books;

            return View();
        }
    }
}

MVC_Demo/Controllers/EmployeeController.cs
using Microsoft.AspNetCore.Mvc;
using MVC_Demo.Models;

namespace MVC_Demo.Controllers
{
    public class EmployeeController : Controller
    {
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(Employee emp)
        {
            return View();
        }
    }
}

MVC_Demo/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MVC_Demo.Models;
using System.Diagnostics;

namespace MVC_Demo.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }
       

        public IActionResult Index()
        {
            ViewData["message"] = "Welecome to MVC Demo";
            List<string> list = new List<string>()
            {
              "Red",
              "Black",
              "Green",
              "Pink",
              "White",
              "Yellow"
            };
            ViewData["colors"]=list;
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }
        public IActionResult AboutUs()
        {
            return View();
        }
        public IActionResult ContactUs()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MVC_Demo/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using MVC_Demo.Models;

namespace MVC_Demo.Controllers
{
    public class ProductController : Controller
    {
        public IActionResult List()
        {
            List<Product> products = new List<Product>()
            {
                new Product{ Id = 1,Name="Pen",Price=20.20},
                new Product{ Id = 2,Name="Pencil",Price=10.20},
                new Product{ Id = 3,Name="MOuse",Price=30.20},
                new Product{ Id = 4,Name="Book",Price=20.20},
                new Product{ Id = 5,Name="Keyboard",Price=20.20},
                new Product{ Id = 6,Name="Pendrive",Price=20.20}
            };
            ViewData["list"] = products;
            ViewBag.List = products;

            return View();
        }
    }
}

MVC_Demo/Controllers/StudentController.cs
using Microsoft.AspNetCore.Mvc;
using MVC_Demo.Models;
using MVC_Demo.Views;

namespace MVC_Demo.Controllers
{
    public class StudentController : Controller
    {
        public IActionResult StudentList()
        {
            List<Student> students = new List<Student>()
            {
                new Student{ Id = 1,Sname="Vidyashree",Marks=50},
                new Student{ Id = 2,Sname="Akshata",Marks=60},
                new Student{ Id = 3,Sname="Anjali",Marks=70},
                new Student{ Id = 4,Sname="Pankaj",Marks=80},
                new Student{ Id = 5,Sname="Sagar",Marks=90},
                new Student{ Id = 6,Sname="Snehal",Marks=95}
            };
            ViewData["list"] = students;
            return View();
        }
    }
}

MVC_Demo/Views/Book/BookList.cshtml
@{
    ViewData["Title"] = "BookList";
}

<h1>BookList</h1>
<table class="table table-bordered">
    <thead>
        <tr>
            <th>Bid</th>
            <th>Bname</th>
            <th>Price</th>
        </tr>
    </thead>
    <tbody>
        @foreach (Book b in (IEnumerable<Book>)ViewData["list"])
        {
            <tr>
                <td>@b.Bid</td>
                <td>@b.Bname</td>
                <td>@b.Price</td>
            </tr>
        }
        <tr>
            <td></td>
            <td></td>
            <td></td>
        </tr>
    </tbody>
</table>

MVC_Demo/Views/Employee/Create.cshtml
@model MVC_Demo.Models.Employee

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Employee</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Age" class="control-label"></label>
                <input asp-for="Age" class="form-control" />
                <span asp-validation-for="Age" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ConfirmPassword" class="control-label"></label>
                <input asp-for="ConfirmPassword" class="form-control" />
                <span asp-validation-for="ConfirmPassword" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Dob" class="control-label"></label>
                <input asp-for="Dob" class="form-control" />
                <span asp-validation-for="Dob" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

MVC_Demo/Views/Home/AboutUs.cshtml
@{
    ViewData["Title"] = "AboutUs";
}

<h1>AboutUs</h1>

MVC_Demo/Views/Home/ContactUs.cshtml
@{
    ViewData["Title"] = "ContactUs";
}

<h1>ContactUs</h1>

MVC_Demo/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
<h4>
    @ViewData["message"]
</h4>
<ol>
    @foreach(string s in (IEnumerable<string>)ViewData["colors"])
    {
        <li>@s</li>
    }
</ol>
<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

MVC_Demo/Views/Product/List.cshtml
@{
    ViewData["Title"] = "List";
}

<h1>List</h1>

<table class="table table-bordered">
    <thead>
        <tr>
            <th>Id</th>
            <th>Name</th>
            <th>Price</th>
        </tr>
    </thead>
    <tbody>
        @foreach(Product p in  (IEnumerable<Product>)ViewData["list"]){
            <tr>
                <td>@p.Id</td>
                <td>@p.Name</td>
                <td>@p.Price</td>
            </tr>
        }
        <tr>
           <td></td>
           <td></td>
           <td></td>
       </tr>
    </tbody>
</table>

<table class="table table-bordered">
    <thead>
        <tr>
            <th>Id</th>
            <th>Name</th>
            <th>Price</th>
        </tr>
    </thead>
    <tbody>
        @foreach (Product p in (IEnumerable<Product>)ViewBag.List)
        {
            <tr>
                <td>@p.Id</td>
                <td>@p.Name</td>
                <td>@p.Price</td>
            </tr>
        }
        <tr>
            <td></td>
            <td></td>
            <td></td>
        </tr>
    </tbody>
</table>

MVC_Demo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MVC_Demo</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MVC_Demo.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MVC_Demo</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="AboutUs">AboutUs</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="ContactUs">ContactUs</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="List">Product List</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Student" asp-action="StudentList">Student List</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Book" asp-action="BookList">Book List</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="Create">Add Employee</a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - MVC_Demo - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MVC_Demo/Views/Student/List.cshtml
@using MVC_Demo.Views;

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<table class="table table-bordered">
    <thead>
        <tr>
            <th>Id</th>
            <th>Sname</th>
            <th>Marks</th>
        </tr>
    </thead>
    <tbody>
        @foreach (Student s in (IEnumerable<Student>)ViewData["list"])
        {
            <tr>
                <td>@s.Id</td>
                <td>@s.Sname</td>
                <td>@s.Marks</td>
            </tr>
        }
        <tr>
            <td></td>
            <td></td>
            <td></td>
        </tr>
    </tbody>
</table>

MVC_Demo/Views/Student/StudentList.cshtml
@using MVC_Demo.Views;

@{
    ViewData["Title"] = "StudentList";
}

<h1>Index</h1>

<table class="table table-bordered">
    <thead>
        <tr>
            <th>Id</th>
            <th>Sname</th>
            <th>Marks</th>
        </tr>
    </thead>
    <tbody>
        @foreach (Student s in (IEnumerable<Student>)ViewData["list"])
        {
            <tr>
                <td>@s.Id</td>
                <td>@s.Sname</td>
                <td>@s.Marks</td>
            </tr>
        }
        <tr>
            <td></td>
            <td></td>
            <td></td>
        </tr>
    </tbody>
</table>